version: '3.7'
services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgres/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
#    ports:
#      - "5433:5433"
    network_mode: "host"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_db
    restart: unless-stopped
    command: ["postgres", "-p", "5433"]
volumes:
  postgres-data:
